"""
contracts.py

Define derived schema versions and required column contracts used by build, checks, and UI compatibility.

Dependencies
------------
- Standard library only in this module.

Classes
-------
- None.

Functions
---------
- None.
"""
from __future__ import annotations

DERIVED_MANIFEST_VERSION = "1.0"
DERIVED_SCHEMA_VERSION = "phase0_thin_slice_v12_retry_before_success"
ACTIVE_CANONICAL_MODULE_CODES = ("M1", "M31", "M32", "M33", "M41", "M42", "M43")

EXPECTED_BASELINE = {
    "parquet_rows": 6_264_394,
    "parquet_columns": 18,
    "parquet_row_groups": 23,
    "catalog_modules": 7,
    "catalog_objectives": 95,
    "catalog_activities": 454,
    "catalog_exercises_unique": 8_862,
    "exercises_count": 8_862,
    "catalog_missing_module_objective_refs": 0,
    "catalog_missing_objective_activity_refs": 0,
    "coverage_overlapping_activity_count": 407,
    "coverage_primary_only_activity_count": 47,
    "coverage_secondary_only_activity_count": 178,
    "coverage_membership_disagreement_count": 75,
    "missing_reference_issue_count": 0,
    "source_disagreement_issue_count": 599,
    "orphan_exercise_count": 497,
    "orphan_secondary_mapping_unique_count": 114,
    "orphan_secondary_mapping_ambiguous_count": 147,
    "rule_ids_missing_in_catalog_count": 0,
    "catalog_modules_missing_in_rules_count": 0,
    "rule_codes_with_multiple_ids_count": 41,
    "rule_ids_with_multiple_codes_count": 41,
    "all_catalog_exercises_in_exercises_json": 1,
}

EXPECTED_SPARSE_NULL_COUNTS = {
    "teacher_id": 135_217,
    "classroom_id": 2_093,
    "login_time": 158_029,
    "session_duration": 158_029,
    "module_long_title": 149,
}

REQUIRED_FACT_COLUMNS = [
    "created_at",
    "date_utc",
    "user_id",
    "classroom_id",
    "playlist_or_module_id",
    "objective_id",
    "objective_label",
    "activity_id",
    "activity_label",
    "exercise_id",
    "data_correct",
    "data_duration",
    "session_duration",
    "work_mode",
    "attempt_number",
    "module_id",
    "module_code",
    "module_label",
]

REQUIRED_AGG_COLUMNS = {
    "hierarchy_context_lookup": [
        "playlist_or_module_id",
        "objective_id",
        "activity_id",
        "exercise_id",
        "module_id",
        "module_code",
        "module_label",
        "objective_label",
        "activity_label",
        "resolution_source_module",
        "resolution_source_objective",
        "resolution_source_activity",
        "attempts",
        "unique_students",
    ],
    "classroom_mode_profiles": [
        "mode_scope",
        "classroom_id",
        "students",
        "activities",
        "objectives",
        "modules",
        "attempts",
        "first_attempt_at",
        "last_attempt_at",
    ],
    "classroom_activity_summary_by_mode": [
        "mode_scope",
        "activity_label",
        "classrooms_observed",
        "attempts_total",
        "successes_total",
        "mean_classroom_success_rate",
        "median_classroom_success_rate",
        "weak_classroom_count",
        "success_rate",
        "weak_classroom_share",
    ],
    "agg_activity_daily": [
        "date_utc",
        "activity_id",
        "activity_label",
        "objective_id",
        "objective_label",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_students",
        "success_rate",
        "first_attempt_success_rate",
        "first_attempt_count",
        "median_duration",
        "repeat_attempt_rate",
        "retry_before_success_rate",
        "avg_attempt_number",
    ],
    "agg_objective_daily": [
        "date_utc",
        "objective_id",
        "objective_label",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_students",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
    ],
    "agg_student_module_progress": [
        "date_utc",
        "user_id",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_activities",
        "success_rate",
        "avg_attempt_number",
        "last_attempt_at",
    ],
    "agg_transition_edges": [
        "date_utc",
        "from_activity_id",
        "from_activity_label",
        "to_activity_id",
        "to_activity_label",
        "transition_count",
        "success_conditioned_count",
        "from_module_id",
        "from_module_code",
        "from_module_label",
    ],
    "agg_module_usage_daily": [
        "date_utc",
        "module_code",
        "module_label",
        "attempts",
        "unique_students",
    ],
    "agg_playlist_module_usage": [
        "playlist_or_module_id",
        "module_code",
        "module_label",
        "work_mode",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_activities",
        "success_rate",
    ],
    "agg_module_activity_usage": [
        "module_code",
        "module_label",
        "activity_id",
        "activity_label",
        "attempts",
        "unique_students",
        "activity_share_within_module",
    ],
    "agg_exercise_daily": [
        "date_utc",
        "module_id",
        "module_code",
        "module_label",
        "objective_id",
        "objective_label",
        "activity_id",
        "activity_label",
        "exercise_id",
        "exercise_label",
        "exercise_type",
        "attempts",
        "unique_students",
        "success_rate",
        "first_attempt_success_rate",
        "first_attempt_count",
        "median_duration",
        "repeat_attempt_rate",
        "retry_before_success_rate",
        "avg_attempt_number",
    ],
    "agg_exercise_elo": [
        "exercise_id",
        "exercise_label",
        "exercise_type",
        "module_id",
        "module_code",
        "module_label",
        "objective_id",
        "objective_label",
        "activity_id",
        "activity_label",
        "exercise_elo",
        "calibration_attempts",
        "calibration_success_rate",
        "calibrated",
    ],
    "agg_exercise_elo_iterative": [
        "exercise_id",
        "exercise_label",
        "exercise_type",
        "module_id",
        "module_code",
        "module_label",
        "objective_id",
        "objective_label",
        "activity_id",
        "activity_label",
        "exercise_elo",
        "calibration_attempts",
        "calibration_success_rate",
        "calibrated",
    ],
    "agg_activity_elo": [
        "module_id",
        "module_code",
        "module_label",
        "objective_id",
        "objective_label",
        "activity_id",
        "activity_label",
        "activity_mean_exercise_elo",
        "calibrated_exercise_count",
        "catalog_exercise_count",
        "calibration_coverage_ratio",
    ],
    "student_elo_events": [
        "user_id",
        "attempt_ordinal",
        "created_at",
        "date_utc",
        "work_mode",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "outcome",
        "expected_success",
        "exercise_elo",
        "student_elo_pre",
        "student_elo_post",
    ],
    "student_elo_profiles": [
        "user_id",
        "module_id",
        "module_code",
        "module_label",
        "total_attempts",
        "first_attempt_at",
        "last_attempt_at",
        "unique_modules",
        "unique_objectives",
        "unique_activities",
        "final_student_elo",
        "eligible_for_replay",
    ],
    "student_elo_events_batch_replay": [
        "user_id",
        "attempt_ordinal",
        "created_at",
        "date_utc",
        "work_mode",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "outcome",
        "expected_success",
        "exercise_elo",
        "student_elo_pre",
        "student_elo_post",
    ],
    "student_elo_profiles_batch_replay": [
        "user_id",
        "module_id",
        "module_code",
        "module_label",
        "total_attempts",
        "first_attempt_at",
        "last_attempt_at",
        "unique_modules",
        "unique_objectives",
        "unique_activities",
        "final_student_elo",
        "eligible_for_replay",
    ],
    "student_elo_events_iterative": [
        "user_id",
        "attempt_ordinal",
        "created_at",
        "date_utc",
        "work_mode",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "outcome",
        "expected_success",
        "exercise_elo",
        "student_elo_pre",
        "student_elo_post",
    ],
    "student_elo_profiles_iterative": [
        "user_id",
        "total_attempts",
        "first_attempt_at",
        "last_attempt_at",
        "unique_modules",
        "unique_objectives",
        "unique_activities",
        "final_student_elo",
        "eligible_for_replay",
    ],
    "zpdes_exercise_progression_events": [
        "user_id",
        "created_at",
        "date_utc",
        "module_id",
        "module_code",
        "module_label",
        "objective_id",
        "objective_label",
        "activity_id",
        "activity_label",
        "exercise_id",
        "work_mode",
        "destination_rank",
        "exercise_first_attempt_outcome",
        "prior_attempt_count",
        "prior_before_activity_attempt_count",
        "prior_same_activity_attempt_count",
        "prior_later_activity_attempt_count",
    ],
    "work_mode_transition_paths": [
        "user_id",
        "first_work_mode",
        "transition_count_total",
        "transition_1_mode",
        "transition_2_mode",
        "transition_3_mode",
        "continues_after_transition_3",
    ],
}

RUNTIME_CORE_COLUMNS = {
    "classroom_mode_profiles": [
        "mode_scope",
        "classroom_id",
        "students",
        "activities",
        "attempts",
    ],
    "classroom_activity_summary_by_mode": [
        "mode_scope",
        "activity_label",
        "classrooms_observed",
        "attempts_total",
        "success_rate",
        "weak_classroom_share",
    ],
    "fact_attempt_core": [
        "created_at",
        "date_utc",
        "user_id",
        "objective_id",
        "activity_id",
        "exercise_id",
        "data_correct",
        "data_duration",
        "attempt_number",
        "module_code",
    ],
    "agg_activity_daily": [
        "date_utc",
        "activity_id",
        "objective_id",
        "module_id",
        "module_code",
        "attempts",
        "unique_students",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
        "retry_before_success_rate",
        "avg_attempt_number",
    ],
    "agg_objective_daily": [
        "date_utc",
        "objective_id",
        "module_id",
        "module_code",
        "attempts",
        "unique_students",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
    ],
    "agg_transition_edges": [
        "date_utc",
        "from_activity_id",
        "to_activity_id",
        "transition_count",
        "success_conditioned_count",
    ],
    "agg_module_usage_daily": [
        "date_utc",
        "module_code",
        "attempts",
        "unique_students",
    ],
    "agg_playlist_module_usage": [
        "playlist_or_module_id",
        "module_code",
        "work_mode",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_activities",
        "success_rate",
    ],
    "agg_module_activity_usage": [
        "module_code",
        "activity_id",
        "attempts",
        "unique_students",
        "activity_share_within_module",
    ],
    "agg_exercise_daily": [
        "date_utc",
        "module_id",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "attempts",
        "unique_students",
        "success_rate",
        "first_attempt_success_rate",
        "first_attempt_count",
        "median_duration",
        "repeat_attempt_rate",
        "retry_before_success_rate",
        "avg_attempt_number",
    ],
    "agg_exercise_elo": [
        "exercise_id",
        "module_id",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_elo",
        "calibration_attempts",
        "calibration_success_rate",
        "calibrated",
    ],
    "agg_exercise_elo_iterative": [
        "exercise_id",
        "module_id",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_elo",
        "calibration_attempts",
        "calibration_success_rate",
        "calibrated",
    ],
    "agg_activity_elo": [
        "module_id",
        "module_code",
        "objective_id",
        "activity_id",
        "activity_mean_exercise_elo",
        "calibrated_exercise_count",
        "catalog_exercise_count",
        "calibration_coverage_ratio",
    ],
    "student_elo_events": [
        "user_id",
        "attempt_ordinal",
        "created_at",
        "date_utc",
        "work_mode",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "outcome",
        "expected_success",
        "exercise_elo",
        "student_elo_pre",
        "student_elo_post",
    ],
    "student_elo_profiles": [
        "user_id",
        "module_code",
        "module_label",
        "total_attempts",
        "first_attempt_at",
        "last_attempt_at",
        "unique_modules",
        "unique_objectives",
        "unique_activities",
        "final_student_elo",
        "eligible_for_replay",
    ],
    "student_elo_events_batch_replay": [
        "user_id",
        "attempt_ordinal",
        "created_at",
        "date_utc",
        "work_mode",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "outcome",
        "expected_success",
        "exercise_elo",
        "student_elo_pre",
        "student_elo_post",
    ],
    "student_elo_profiles_batch_replay": [
        "user_id",
        "module_code",
        "module_label",
        "total_attempts",
        "first_attempt_at",
        "last_attempt_at",
        "unique_modules",
        "unique_objectives",
        "unique_activities",
        "final_student_elo",
        "eligible_for_replay",
    ],
    "student_elo_events_iterative": [
        "user_id",
        "attempt_ordinal",
        "created_at",
        "date_utc",
        "work_mode",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "outcome",
        "expected_success",
        "exercise_elo",
        "student_elo_pre",
        "student_elo_post",
    ],
    "student_elo_profiles_iterative": [
        "user_id",
        "total_attempts",
        "first_attempt_at",
        "last_attempt_at",
        "unique_modules",
        "unique_objectives",
        "unique_activities",
        "final_student_elo",
        "eligible_for_replay",
    ],
    "zpdes_exercise_progression_events": [
        "user_id",
        "created_at",
        "date_utc",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "work_mode",
        "destination_rank",
        "exercise_first_attempt_outcome",
        "prior_attempt_count",
        "prior_before_activity_attempt_count",
        "prior_same_activity_attempt_count",
        "prior_later_activity_attempt_count",
    ],
    "work_mode_transition_paths": [
        "user_id",
        "first_work_mode",
        "transition_count_total",
        "transition_1_mode",
        "transition_2_mode",
        "transition_3_mode",
        "continues_after_transition_3",
    ],
}

RUNTIME_LABEL_COLUMNS = {
    "fact_attempt_core": [
        "module_label",
        "objective_label",
        "activity_label",
    ],
    "agg_activity_daily": [
        "module_label",
        "objective_label",
        "activity_label",
    ],
    "agg_objective_daily": [
        "module_label",
        "objective_label",
    ],
    "agg_transition_edges": [
        "from_activity_label",
        "to_activity_label",
        "from_module_label",
    ],
    "agg_module_usage_daily": [
        "module_label",
    ],
    "agg_playlist_module_usage": [
        "module_label",
    ],
    "agg_module_activity_usage": [
        "module_label",
        "activity_label",
    ],
    "agg_exercise_daily": [
        "module_label",
        "objective_label",
        "activity_label",
        "exercise_label",
    ],
    "agg_exercise_elo": [
        "module_label",
        "objective_label",
        "activity_label",
        "exercise_label",
    ],
    "agg_exercise_elo_iterative": [
        "module_label",
        "objective_label",
        "activity_label",
        "exercise_label",
    ],
    "agg_activity_elo": [
        "module_label",
        "objective_label",
        "activity_label",
    ],
    "zpdes_exercise_progression_events": [
        "module_label",
        "objective_label",
        "activity_label",
    ],
}
