from __future__ import annotations

DERIVED_MANIFEST_VERSION = "1.0"
DERIVED_SCHEMA_VERSION = "phase0_thin_slice_v2_labels"
ACTIVE_CANONICAL_MODULE_CODES = ("M1", "M31", "M32", "M33", "M41", "M42", "M43")

EXPECTED_BASELINE = {
    "parquet_rows": 6_264_394,
    "parquet_columns": 18,
    "parquet_row_groups": 23,
    "catalog_modules": 7,
    "catalog_objectives": 95,
    "catalog_activities": 454,
    "catalog_exercises_unique": 8_862,
    "exercises_count": 8_862,
    "catalog_missing_module_objective_refs": 0,
    "catalog_missing_objective_activity_refs": 0,
    "coverage_overlapping_activity_count": 407,
    "coverage_primary_only_activity_count": 47,
    "coverage_secondary_only_activity_count": 178,
    "coverage_membership_disagreement_count": 75,
    "missing_reference_issue_count": 0,
    "source_disagreement_issue_count": 599,
    "orphan_exercise_count": 497,
    "orphan_secondary_mapping_unique_count": 114,
    "orphan_secondary_mapping_ambiguous_count": 147,
    "rule_ids_missing_in_catalog_count": 0,
    "catalog_modules_missing_in_rules_count": 0,
    "rule_codes_with_multiple_ids_count": 41,
    "rule_ids_with_multiple_codes_count": 41,
    "all_catalog_exercises_in_exercises_json": 1,
}

EXPECTED_SPARSE_NULL_COUNTS = {
    "teacher_id": 135_217,
    "classroom_id": 2_093,
    "login_time": 158_029,
    "session_duration": 158_029,
    "module_long_title": 149,
}

REQUIRED_FACT_COLUMNS = [
    "created_at",
    "date_utc",
    "user_id",
    "teacher_id",
    "classroom_id",
    "playlist_or_module_id",
    "objective_id",
    "objective_label",
    "activity_id",
    "activity_label",
    "exercise_id",
    "module_long_title",
    "data_correct",
    "data_duration",
    "session_duration",
    "work_mode",
    "attempt_number",
    "student_attempt_index",
    "first_attempt_success_rate",
    "module_id",
    "module_code",
    "module_label",
]

REQUIRED_AGG_COLUMNS = {
    "agg_activity_daily": [
        "date_utc",
        "activity_id",
        "activity_label",
        "objective_id",
        "objective_label",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_students",
        "success_rate",
        "first_attempt_success_rate",
        "first_attempt_count",
        "median_duration",
        "repeat_attempt_rate",
        "avg_attempt_number",
    ],
    "agg_objective_daily": [
        "date_utc",
        "objective_id",
        "objective_label",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_students",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
    ],
    "agg_student_module_progress": [
        "date_utc",
        "user_id",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_activities",
        "success_rate",
        "avg_attempt_number",
        "last_attempt_at",
    ],
    "agg_transition_edges": [
        "date_utc",
        "from_activity_id",
        "from_activity_label",
        "to_activity_id",
        "to_activity_label",
        "transition_count",
        "success_conditioned_count",
        "from_module_id",
        "from_module_code",
        "from_module_label",
    ],
    "agg_module_usage_daily": [
        "date_utc",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_playlists",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
    ],
    "agg_student_module_exposure": [
        "user_id",
        "module_id",
        "module_code",
        "module_label",
        "attempts",
        "unique_activities",
        "active_days",
        "total_time_seconds",
        "is_effective_user",
        "exposure_bucket",
    ],
    "agg_playlist_module_usage": [
        "playlist_or_module_id",
        "module_id",
        "module_code",
        "module_label",
        "work_mode",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_activities",
        "success_rate",
        "median_duration",
    ],
    "agg_module_activity_usage": [
        "module_id",
        "module_code",
        "module_label",
        "activity_id",
        "activity_label",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_playlists",
        "activity_share_within_module",
    ],
    "agg_exercise_daily": [
        "date_utc",
        "module_id",
        "module_code",
        "module_label",
        "objective_id",
        "objective_label",
        "activity_id",
        "activity_label",
        "exercise_id",
        "exercise_label",
        "exercise_type",
        "attempts",
        "unique_students",
        "success_rate",
        "first_attempt_success_rate",
        "first_attempt_count",
        "median_duration",
        "repeat_attempt_rate",
        "avg_attempt_number",
    ],
}

RUNTIME_CORE_COLUMNS = {
    "fact_attempt_core": [
        "created_at",
        "date_utc",
        "user_id",
        "objective_id",
        "activity_id",
        "exercise_id",
        "data_correct",
        "data_duration",
        "attempt_number",
        "module_code",
    ],
    "agg_activity_daily": [
        "date_utc",
        "activity_id",
        "objective_id",
        "module_id",
        "module_code",
        "attempts",
        "unique_students",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
        "avg_attempt_number",
    ],
    "agg_objective_daily": [
        "date_utc",
        "objective_id",
        "module_id",
        "module_code",
        "attempts",
        "unique_students",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
    ],
    "agg_transition_edges": [
        "date_utc",
        "from_activity_id",
        "to_activity_id",
        "transition_count",
        "success_conditioned_count",
    ],
    "agg_module_usage_daily": [
        "date_utc",
        "module_id",
        "module_code",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_playlists",
        "success_rate",
        "median_duration",
        "repeat_attempt_rate",
    ],
    "agg_student_module_exposure": [
        "user_id",
        "module_id",
        "module_code",
        "attempts",
        "unique_activities",
        "active_days",
        "total_time_seconds",
        "is_effective_user",
        "exposure_bucket",
    ],
    "agg_playlist_module_usage": [
        "playlist_or_module_id",
        "module_id",
        "module_code",
        "work_mode",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_activities",
        "success_rate",
        "median_duration",
    ],
    "agg_module_activity_usage": [
        "module_id",
        "module_code",
        "activity_id",
        "attempts",
        "unique_students",
        "unique_classrooms",
        "unique_playlists",
        "activity_share_within_module",
    ],
    "agg_exercise_daily": [
        "date_utc",
        "module_id",
        "module_code",
        "objective_id",
        "activity_id",
        "exercise_id",
        "attempts",
        "unique_students",
        "success_rate",
        "first_attempt_success_rate",
        "first_attempt_count",
        "median_duration",
        "repeat_attempt_rate",
        "avg_attempt_number",
    ],
}

RUNTIME_LABEL_COLUMNS = {
    "fact_attempt_core": [
        "module_label",
        "objective_label",
        "activity_label",
    ],
    "agg_activity_daily": [
        "module_label",
        "objective_label",
        "activity_label",
    ],
    "agg_objective_daily": [
        "module_label",
        "objective_label",
    ],
    "agg_transition_edges": [
        "from_activity_label",
        "to_activity_label",
        "from_module_label",
    ],
    "agg_module_usage_daily": [
        "module_label",
    ],
    "agg_student_module_exposure": [
        "module_label",
    ],
    "agg_playlist_module_usage": [
        "module_label",
    ],
    "agg_module_activity_usage": [
        "module_label",
        "activity_label",
    ],
    "agg_exercise_daily": [
        "module_label",
        "objective_label",
        "activity_label",
        "exercise_label",
    ],
}
